using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DependencyInjection
{
    public class Program
    {
        public static void Main(string[] args)
        {
            IEmailService emailService = new EmailService();

            // ******Create an instance of the notification service with the email service dependency injected*****************
            //var notification = new Notification(emailService); 

            //Notification.SendNotification("sachin.shukla007@gmail.com","Hey this is and autogenerated email!");

            var notification = new Notification();

            //notification._emailService = emailService; // Dependency injection via property injection 

            notification.setNotification(emailService);

            notification.SendNotification("sachin.shukla007@gmail.com", "Hey this is and autogenerated email!");

            Console.WriteLine("**********************ILoggger Dependency Injection*******************************");

            var loggerFilenameManager = new LoggerFilenameManager();
            var fileLogger = new FileLogger(loggerFilenameManager);
            var loggerManager = new LoggerManager(fileLogger);

            loggerManager.LogMessage("Error Detected!");
            loggerManager.Dispose();
        }
    }
}
